config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :games, only: [:create, :index, :show, :update, :new] do
    resources :pieces, only: [:destroy, :index, :show, :update]
  end

  namespace :sample do
    resources :games, only: [:create, :index, :show, :update, :new] do
      resources :pieces, only: [:destroy, :index, :show, :update]
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<br />
<div class="row align-center">
  <div class="head small-3 small-centered columns">
    <%= link_to "PLAY SAMPLE GAME", sample_games_path, method: :post, class: "button large", id: "newSampleGameButton" %>
    <h4 style="text-align:center;">OR</h4>
    <% if user_signed_in? %>
      <%= link_to "CREATE NEW GAME!", new_game_path, class: "button large", id: "newGameButton" %>
      <h4 style="text-align:center;">OR</h4>
      <%= link_to "JOIN A GAME!", games_path, method: :get, class: "button large", id: "joinGameButton" %>
      <h4 style="text-align:center;">OR</h4>
      <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "button large" %>
    <% else %>
      <%= link_to "SIGN UP", new_user_registration_path, class: "button large" %>
      <h4 style="text-align:center;">OR</h4>
      <%= link_to "SIGN IN", new_user_session_path, class: "button large" %>
    <% end %>
  </div>
</div>
<br />