config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :games, only: [:create, :index, :show, :update, :new] do
    resources :pieces, only: [:destroy, :index, :show, :update]
  end

  namespace :sample do
    resources :games, only: [:create, :index, :show, :update, :new] do
      resources :pieces, only: [:destroy, :index, :show, :update]
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :pawns
  has_many :rooks
  has_many :knights
  has_many :bishops
  has_many :kings
  has_many :queens
  has_many :pieces
  scope :available,  -> { where(black_player_id: nil) }
  scope :not_sample, -> { where.not(white_player_id: nil) }

  def start
    self.update_attribute(:state, "In Progress")
    self.update_attribute(:player_whites_turn, true)
  end

  def change_player_turn
    self.toggle!(:player_whites_turn)
  end

  def active_color
    player_whites_turn == true ? "white" : "black"
  end

  def check_square(x, y)
    self.pieces.find_by(x_position: x, y_position: y)
  end

  def board_in_check?
    king = self.kings.find_by(color: active_color)
    if inactive_player_valid_moves.include?({x: king.x_position, y: king.y_position})
      self.update_attribute(:state, "Check")
      check_for_checkmate(king)
    else
      self.update_attribute(:state, "In Progress")
    end
    self.state == "Check" || self.state == "Checkmate" ? true : false
  end

  def move_into_check(x,y)
    inactive_player_valid_moves.include?({x: x, y: y})
  end

  def has_enemy_pawns_diagonal(x,y,color)
    king = self.kings.find_by(color: color)
    if king.is_white_piece?
      diagonal_east_piece = check_square(x+1,y+1)
      diagonal_west_piece = check_square(x-1,y+1)
    else
      diagonal_east_piece = check_square(x+1,y-1)
      diagonal_west_piece = check_square(x-1,y-1)
    end
    if king.is_enemy(diagonal_east_piece)
      return true if diagonal_east_piece.is_a? Pawn
    elsif king.is_enemy(diagonal_west_piece)
      return true if diagonal_west_piece.is_a? Pawn
    else
      return false
    end
  end

  def populate_white_side
    populate_white_pawns
    populate_white_rooks
    populate_white_knights
    populate_white_bishops
    populate_white_king_and_queen
  end

  def populate_black_side
    populate_black_pawns
    populate_black_rooks
    populate_black_knights
    populate_black_bishops
    populate_black_king_and_queen
  end

  def populate_white_pawns
    8.times do |column|
      self.pawns.create(x_position: column+1, y_position: 2, player_id: white_player_id, color: "white")
    end
  end

private
  def check_for_checkmate(king)
    possible_moves = king.valid_moves.keep_if { |move| king.in_boundary?(move[:x], move[:y]) }
    if possible_moves & inactive_player_valid_moves == possible_moves
      self.update_attribute(:state, "Checkmate")
      self.lock!
      self.pieces.each { |piece| piece.lock! }
    end
  end

  def inactive_player_valid_moves
    @inactive_player_valid_moves = []
    pieces = self.pieces.where.not(color: active_color)
    pieces.each do |piece|
      moves = piece.valid_moves
      moves.each { |move| @inactive_player_valid_moves.push(move) }
    end
    @inactive_player_valid_moves
  end

  def populate_black_pawns
    8.times do |column|
      self.pawns.create(x_position: column+1, y_position: 7, player_id: black_player_id, color: "black")
    end
  end

  def populate_white_rooks
    [1,8].each do |column|
      self.rooks.create(x_position: column, y_position: 1, player_id: white_player_id, color: "white")
    end
  end

  def populate_black_rooks
    [1,8].each do |column|
      self.rooks.create(x_position: column, y_position: 8, player_id: black_player_id, color: "black")
    end
  end

  def populate_white_knights
    [2,7].each do |column|
      self.knights.create(x_position: column, y_position: 1, player_id: white_player_id, color: "white")
    end
  end

  def populate_black_knights
    [2,7].each do |column|
      self.knights.create(x_position: column, y_position: 8, player_id: black_player_id, color: "black")
    end
  end

  def populate_white_bishops
    [3,6].each do |column|
      self.bishops.create(x_position: column, y_position: 1, player_id: white_player_id, color: "white")
    end
  end

  def populate_black_bishops
    [3,6].each do |column|
      self.bishops.create(x_position: column, y_position: 8, player_id: black_player_id, color: "black")
    end
  end

  def populate_white_king_and_queen
    self.kings.create(x_position: 5, y_position: 1, player_id: white_player_id, color: "white")
    self.queens.create(x_position: 4, y_position: 1, player_id: white_player_id, color: "white")
  end

  def populate_black_king_and_queen
    self.kings.create(x_position: 5, y_position: 8, player_id: black_player_id, color: "black")
    self.queens.create(x_position: 4, y_position: 8, player_id: black_player_id, color: "black")
  end

  def populate_row(row)
    8.times do |column|
      self.pieces.create(x_position: column+1, y_position: row)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def index
    @games = Game.not_sample.available.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params.merge(white_player_id: current_user.id))
    @game.populate_white_side
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
    @player_white = User.find_by(id: @game.white_player_id)
    @player_black = User.find_by(id: @game.black_player_id)
  end

  def update
    game = Game.find(params[:id])
    if game.white_player_id != current_user.id
      game.update(black_player_id: current_user.id)
      game.populate_black_side
      game.start
    end
    redirect_to game_path(game)
  end

private
  def game_params
    params.require(:game).permit(:name, :white_player_id, :black_player_id)
  end
end

app/controllers/sample/games_controller.rb
class Sample::GamesController < ApplicationController

  require 'faker'

  def create
    @game = Game.create()
    @game.populate_white_side
    @game.populate_black_side
    @game.start
    redirect_to sample_game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
    @player_white = {username: generate_random_name}
    @player_black = {username: generate_random_name}
    @game.update(name: "#{@player_white[:username]} VS #{@player_black[:username]}")
    render template: "games/show"
  end

private

  def generate_random_name
    selections = [
      Faker::Artist.name,
      Faker::FunnyName.name,
      Faker::GreekPhilosophers.name,
      Faker::Superhero.name,
      Faker::Beer.name
    ]
    selections.sample
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sample/games_helper.rb
module Sample::GamesHelper
end

app/views/games/index.html.erb
<br />
<div class="grid-x align-center">
  <div class="cell large-6">
    <table class="hover">
      <thead>
        <th width="80">Join</th>
        <th width="400">Game</th>
        <th width="120">Player Waiting</th>
      </thead>
      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= link_to 'Join Game', game_path(game), method: :patch %></td>
          <td><%= game.name %></td>
          <td><%= User.find_by(id: game.white_player_id).username %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/games/new.html.erb
<h1>Start a New Game!</h1>
<%= simple_form_for @game do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/show.html.erb
<script src="https://cdn.jsdelivr.net/gh/mathusummut/confetti.js/confetti.min.js"></script>
<script>
document.addEventListener("DOMContentLoaded", function(){
  let activePiece;
  let destinationSquare;
  let activeColor;
  let gameStateDiv = document.getElementById("state");
  let activePlayer;

  let fetchBoard = fetch("<%= game_pieces_path(@game) %>");

  function renderInitialBoard (boardState) {
    updateGameState(boardState)
    pieces = boardState.pieces;
    pieces.forEach( piece => {
      if (piece.x_position && piece.y_position) {
        let [x, y] = [piece.x_position, piece.y_position];
        let boardSquare = document.querySelector(`[data-x='${x}'][data-y='${y}']`);
        boardSquare.innerHTML = piece.image;
        boardSquare.setAttribute('data-piece-id', piece.id);
        boardSquare.setAttribute('data-color', piece.color);
        boardSquare.addEventListener("click", updateActivePiece);
      }
    });
  }

  function updateGameState(game_data) {
    document.querySelector(".active-player").classList.remove("active-player")
    gameStateDiv.innerHTML = game_data.state
    if (game_data.state == "Checkmate") {
      winnerDiv = document.getElementById(`player-${activeColor}-winner`);
      homeBtn = document.getElementById("home");
      winnerDiv.classList.remove("hidden");
      homeBtn.classList.remove("hidden");
      activeColor = null;
      confetti.start();
    } else {
      activeColor = game_data.active_color;
      document.getElementById(`player-${activeColor}`).classList.add("active-player");
    }
  }

  function updateActivePiece() {
    if (!activePiece && event.target.dataset.color == activeColor) {
      activePiece = event.target;
      activePiece.classList.add("initial");
    }
  }

  fetchBoard
    .then(response => response.json())
    .then (json => renderInitialBoard(json))
    .catch(error => console.log(error));



  function submitMove() {
    let [newX, newY] = [destinationSquare.dataset.x, destinationSquare.dataset.y]
    let piecePayload = {piece: {
      x_position: newX,
      y_position: newY,
      }
    }
    submitPieceUpdate(activePiece.dataset.pieceId, piecePayload)
      .then(response => checkMove(response))
      .then(game_response => updateGameState(game_response))
      .catch(error => console.log(error));
  }

  function submitPieceUpdate(pieceID, data) {
    let gameID = "<%= @game.id %>";
    return fetch("/games/" + gameID + "/pieces/" + pieceID, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data),
    });
  }

  function checkMove(response) {
    if (response.status === 200) {
      game_response = response.json();
      updatePieceLocation();
      clearSelections();
      return game_response;
    } else {
      alert("That is not a valid move");
      return new Promise((resolve, reject) => {
        clearSelections();
        reject("Please check the Network for Errors");
      });
    }    
  }

  function clearSelections() {
    activePiece.classList.remove("initial");
    document.querySelector(".destination").classList.remove("destination");
    activePiece = null;
    destinationSquare = null;
    document.querySelector(".clear-submit").classList.add("hidden");
  }

  function updatePieceLocation() {
    let initialSquare = activePiece;
    destinationSquare.innerHTML = initialSquare.innerHTML;
    destinationSquare.setAttribute("data-color", activeColor);
    destinationSquare.setAttribute("data-piece-id", initialSquare.dataset.pieceId); 
    destinationSquare.addEventListener("click", updateActivePiece);

    initialSquare.innerHTML = "";
    initialSquare.removeAttribute("data-color");
    initialSquare.removeAttribute("data-piece-id");
    initialSquare.removeEventListener("click", updateActivePiece);
  }

  document.querySelectorAll('.box').forEach( box => {
    box.addEventListener("click", function(event) {
      if (activePiece) {
        destinationSquare = event.target;
        document.querySelector(".clear-submit").classList.remove("hidden");
        if (document.querySelector(".destination")) {
          document.querySelector(".destination").classList.remove("destination");
        }
        destinationSquare.classList.add("destination");
      }
    });
  });

  document.querySelector(".wipe").addEventListener("click", clearSelections)
  document.querySelector(".submit").addEventListener("click", submitMove)

});
</script>

<br />

<div class="text-center">
  <h1><%= @game.name %></h1>
  <h2 id="state"></h2>
</div>


<div class="grid-x grid-padding-x align-spaced">
  <div class="cell large-3 text-center">
    <h3>Player 1</h3>
    <h2 class="active-player" id="player-white">
      <%= @player_white[:username] %>
    </h2>
    <div class="winner hidden" id="player-white-winner">
      <i>&#9813</i>
      <h3>WINNER</h3>
    </div>
  </div>

  <div class="cell large-auto">
    <div class="row align-center">
      <div class="wrapper">
        <div class="box-inner"></div>
        <div class="box-inner">A</div>
        <div class="box-inner">B</div>
        <div class="box-inner">C</div>
        <div class="box-inner">D</div>
        <div class="box-inner">E</div>
        <div class="box-inner">F</div>
        <div class="box-inner">G</div>
        <div class="box-inner">H</div>
        <div class="box-inner"></div>
      
        <div class="box-inner">8</div>
        <div class="box white"       data-x = "1" data-y = "8"></div>
        <div class="box"             data-x = "2" data-y = "8"></div>
        <div class="box white"       data-x = "3" data-y = "8"></div>
        <div class="box"             data-x = "4" data-y = "8"></div>
        <div class="box white"       data-x = "5" data-y = "8"></div>
        <div class="box"             data-x = "6" data-y = "8"></div>
        <div class="box white"       data-x = "7" data-y = "8"></div>
        <div class="box"             data-x = "8" data-y = "8"></div>
        <div class="box-inner">8</div>


        <div class="box-inner">7</div>
        <div class="box"             data-x="1" data-y="7"></div>
        <div class="box white"       data-x="2" data-y="7"></div>
        <div class="box"             data-x="3" data-y="7"></div>
        <div class="box white"       data-x="4" data-y="7"></div>
        <div class="box"             data-x="5" data-y="7"></div>
        <div class="box white"       data-x="6" data-y="7"></div>
        <div class="box"             data-x="7" data-y="7"></div>
        <div class="box white"       data-x="8" data-y="7"></div>
        <div class="box-inner">7</div>

        <div class="box-inner">6</div>
        <div class="box white"       data-x = "1" data-y = "6"></div>
        <div class="box"             data-x = "2" data-y = "6"></div>
        <div class="box white"       data-x = "3" data-y = "6"></div>
        <div class="box"             data-x = "4" data-y = "6"></div>
        <div class="box white"       data-x = "5" data-y = "6"></div>
        <div class="box"             data-x = "6" data-y = "6"></div>
        <div class="box white"       data-x = "7" data-y = "6"></div>
        <div class="box"             data-x = "8" data-y = "6"></div>
        <div class="box-inner">6</div>

        <div class="box-inner">5</div>
        <div class="box"             data-x="1" data-y="5"></div>
        <div class="box white"       data-x="2" data-y="5"></div>
        <div class="box"             data-x="3" data-y="5"></div>
        <div class="box white"       data-x="4" data-y="5"></div>
        <div class="box"             data-x="5" data-y="5"></div>
        <div class="box white"       data-x="6" data-y="5"></div>
        <div class="box"             data-x="7" data-y="5"></div>
        <div class="box white"       data-x="8" data-y="5"></div>
        <div class="box-inner">5</div>

        <div class="box-inner">4</div>
        <div class="box white"       data-x = "1" data-y = "4"></div>
        <div class="box"             data-x = "2" data-y = "4"></div>
        <div class="box white"       data-x = "3" data-y = "4"></div>
        <div class="box"             data-x = "4" data-y = "4"></div>
        <div class="box white"       data-x = "5" data-y = "4"></div>
        <div class="box"             data-x = "6" data-y = "4"></div>
        <div class="box white"       data-x = "7" data-y = "4"></div>
        <div class="box"             data-x = "8" data-y = "4"></div>
        <div class="box-inner">4</div>

        <div class="box-inner">3</div>
        <div class="box"             data-x="1" data-y="3"></div>
        <div class="box white"       data-x="2" data-y="3"></div>
        <div class="box"             data-x="3" data-y="3"></div>
        <div class="box white"       data-x="4" data-y="3"></div>
        <div class="box"             data-x="5" data-y="3"></div>
        <div class="box white"       data-x="6" data-y="3"></div>
        <div class="box"             data-x="7" data-y="3"></div>
        <div class="box white"       data-x="8" data-y="3"></div>
        <div class="box-inner">3</div>

        <div class="box-inner">2</div>
        <div class="box white"       data-x = "1" data-y = "2"></div>
        <div class="box"             data-x = "2" data-y = "2"></div>
        <div class="box white"       data-x = "3" data-y = "2"></div>
        <div class="box"             data-x = "4" data-y = "2"></div>
        <div class="box white"       data-x = "5" data-y = "2"></div>
        <div class="box"             data-x = "6" data-y = "2"></div>
        <div class="box white"       data-x = "7" data-y = "2"></div>
        <div class="box"             data-x = "8" data-y = "2"></div>
        <div class="box-inner">2</div>

        <div class="box-inner">1</div>
        <div class="box"             data-x="1" data-y="1"></div>
        <div class="box white"       data-x="2" data-y="1"></div>
        <div class="box"             data-x="3" data-y="1"></div>
        <div class="box white"       data-x="4" data-y="1"></div>
        <div class="box"             data-x="5" data-y="1"></div>
        <div class="box white"       data-x="6" data-y="1"></div>
        <div class="box"             data-x="7" data-y="1"></div>
        <div class="box white"       data-x="8" data-y="1"></div>
        <div class="box-inner">1</div>
        
        <div class="box-inner"></div>
        <div class="box-inner">A</div>
        <div class="box-inner">B</div>
        <div class="box-inner">C</div>
        <div class="box-inner">D</div>
        <div class="box-inner">E</div>
        <div class="box-inner">F</div>
        <div class="box-inner">G</div>
        <div class="box-inner">H</div>
        <div class="box-inner"></div>
      </div>
    </div>
  </div>

  <div class="cell large-3 text-center">
    <% if @player_black %>
      <h3>Player 2</h3>
      <h2 id="player-black">
        <%= @player_black[:username] %>
      </h2>
      <div class="winner hidden" id="player-black-winner">
        <i>&#9813</i>
        <h3>WINNER</h3>
      </div>
    <% else %>
      <h3> Searching for Opponent...</h3>
    <% end %>
  </div>
</div>

<div class="grid-x clear-submit hidden align-center">
  <div class="cell small-3">
    <button class="button large wipe">Clear</button>
  </div><br />
  <div class="cell small-3">
    <button class="button large submit">Submit</button>
  </div>
</div>

<br />

<div class="grid-x align-center">
  <div class="cell small-3 hidden" id="home">
    <%= link_to "HOME", root_path, class: "button large submit" %>
  </div>
</div>


